obj-y                   := core.o sata.o wdt.o
obj-$(CONFIG_SMP)           += platsmp.o headsmp.o
obj-$(CONFIG_HOTPLUG_CPU)       += hotplug.o
obj-$(CONFIG_XMMAC_ETH) += xmmac/

#obj-$(CONFIG_XM580_RTC) += rtc/
#obj-$(CONFIG_XM580_AUDIO) += i2s/
#obj-$(CONFIG_XM580_AUDIO) += acodec/
#obj-$(CONFIG_XM580_VO) += vo/
#obj-y += i2c/
obj-$(CONFIG_MXC_HANTRO) += handrodec/
#obj-y += ddr.o